//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace FPar.GEXF {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="attributes-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("attributes", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class attributescontent {
        
        private attributecontent[] attributeField;
        
        private classtype classField;
        
        private modetype modeField;
        
        private bool modeFieldSpecified;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attribute")]
        public attributecontent[] attribute {
            get {
                return this.attributeField;
            }
            set {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public classtype @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public modetype mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="attribute-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("attribute", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class attributecontent {
        
        private string[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        private string idField;
        
        private string titleField;
        
        private attrtypetype typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("default", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("options", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public attrtypetype type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gexf.net/1.2draft", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        @default,
        
        /// <remarks/>
        options,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="attrtype-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum attrtypetype {
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        @long,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        @float,
        
        /// <remarks/>
        boolean,
        
        /// <remarks/>
        liststring,
        
        /// <remarks/>
        @string,
        
        /// <remarks/>
        anyURI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="node-shape-content", Namespace="http://www.gexf.net/1.2draft/viz")]
    public partial class nodeshapecontent {
        
        private spell[] spellsField;
        
        private nodeshapetype valueField;
        
        private string uriField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
        public spell[] spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public nodeshapetype value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class spell {
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="node-shape-type", Namespace="http://www.gexf.net/1.2draft/viz")]
    public enum nodeshapetype {
        
        /// <remarks/>
        disc,
        
        /// <remarks/>
        square,
        
        /// <remarks/>
        triangle,
        
        /// <remarks/>
        diamond,
        
        /// <remarks/>
        image,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="edge-shape-content", Namespace="http://www.gexf.net/1.2draft/viz")]
    public partial class edgeshapecontent {
        
        private spell[] spellsField;
        
        private edgeshapetype valueField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
        public spell[] spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public edgeshapetype value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="edge-shape-type", Namespace="http://www.gexf.net/1.2draft/viz")]
    public enum edgeshapetype {
        
        /// <remarks/>
        solid,
        
        /// <remarks/>
        dotted,
        
        /// <remarks/>
        dashed,
        
        /// <remarks/>
        @double,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="class-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum classtype {
        
        /// <remarks/>
        node,
        
        /// <remarks/>
        edge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="mode-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum modetype {
        
        /// <remarks/>
        @static,
        
        /// <remarks/>
        dynamic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nodes-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("nodes", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class nodescontent {
        
        private nodecontent[] nodeField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("node")]
        public nodecontent[] node {
            get {
                return this.nodeField;
            }
            set {
                this.nodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="node-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("node", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class nodecontent {
        
        private object[] itemsField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        private string pidField;
        
        private string idField;
        
        private string labelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attvalues", typeof(attvaluescontent))]
        [System.Xml.Serialization.XmlElementAttribute("color", typeof(colorcontent))]
        [System.Xml.Serialization.XmlElementAttribute("edges", typeof(edgescontent))]
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(nodescontent))]
        [System.Xml.Serialization.XmlElementAttribute("parents", typeof(parentscontent))]
        [System.Xml.Serialization.XmlElementAttribute("position", typeof(positioncontent))]
        [System.Xml.Serialization.XmlElementAttribute("shape", typeof(nodeshapecontent))]
        [System.Xml.Serialization.XmlElementAttribute("size", typeof(sizecontent))]
        [System.Xml.Serialization.XmlElementAttribute("spells", typeof(spellscontent))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="attvalues-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("attvalues", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class attvaluescontent {
        
        private attvalue[] attvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attvalue")]
        public attvalue[] attvalue {
            get {
                return this.attvalueField;
            }
            set {
                this.attvalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class attvalue {
        
        private string forField;
        
        private string valueField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @for {
            get {
                return this.forField;
            }
            set {
                this.forField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="color-content", Namespace="http://www.gexf.net/1.2draft/viz")]
    [System.Xml.Serialization.XmlRootAttribute("color", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class colorcontent {
        
        private spell[] spellsField;
        
        private string rField;
        
        private string gField;
        
        private string bField;
        
        private float aField;
        
        private bool aFieldSpecified;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
        public spell[] spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float a {
            get {
                return this.aField;
            }
            set {
                this.aField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aSpecified {
            get {
                return this.aFieldSpecified;
            }
            set {
                this.aFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="edges-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("edges", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class edgescontent {
        
        private edgecontent[] edgeField;
        
        private string countField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("edge")]
        public edgecontent[] edge {
            get {
                return this.edgeField;
            }
            set {
                this.edgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="edge-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("edge", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class edgecontent {
        
        private object[] itemsField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        private string idField;
        
        private edgetypetype typeField;
        
        private bool typeFieldSpecified;
        
        private string labelField;
        
        private string sourceField;
        
        private string targetField;
        
        private float weightField;
        
        private bool weightFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attvalues", typeof(attvaluescontent))]
        [System.Xml.Serialization.XmlElementAttribute("color", typeof(colorcontent))]
        [System.Xml.Serialization.XmlElementAttribute("shape", typeof(edgeshapecontent))]
        [System.Xml.Serialization.XmlElementAttribute("spells", typeof(spellscontent))]
        [System.Xml.Serialization.XmlElementAttribute("thickness", typeof(thicknesscontent))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public edgetypetype type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool weightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="spells-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("spells", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class spellscontent {
        
        private spell[] spellField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("spell")]
        public spell[] spell {
            get {
                return this.spellField;
            }
            set {
                this.spellField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="thickness-content", Namespace="http://www.gexf.net/1.2draft/viz")]
    [System.Xml.Serialization.XmlRootAttribute("thickness", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class thicknesscontent {
        
        private spell[] spellsField;
        
        private float valueField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
        public spell[] spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="edgetype-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum edgetypetype {
        
        /// <remarks/>
        directed,
        
        /// <remarks/>
        undirected,
        
        /// <remarks/>
        mutual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="parents-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("parents", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class parentscontent {
        
        private parent[] parentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parent")]
        public parent[] parent {
            get {
                return this.parentField;
            }
            set {
                this.parentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class parent {
        
        private string forField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @for {
            get {
                return this.forField;
            }
            set {
                this.forField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="position-content", Namespace="http://www.gexf.net/1.2draft/viz")]
    [System.Xml.Serialization.XmlRootAttribute("position", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class positioncontent {
        
        private spell[] spellsField;
        
        private float xField;
        
        private float yField;
        
        private float zField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
        public spell[] spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="size-content", Namespace="http://www.gexf.net/1.2draft/viz")]
    [System.Xml.Serialization.XmlRootAttribute("size", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class sizecontent {
        
        private spell[] spellsField;
        
        private float valueField;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("spell", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
        public spell[] spells {
            get {
                return this.spellsField;
            }
            set {
                this.spellsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="gexf-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("gexf", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class gexfcontent {
        
        private metacontent metaField;
        
        private graphcontent graphField;
        
        private gexfcontentVersion versionField;
        
        private string variantField;
        
        /// <remarks/>
        public metacontent meta {
            get {
                return this.metaField;
            }
            set {
                this.metaField = value;
            }
        }
        
        /// <remarks/>
        public graphcontent graph {
            get {
                return this.graphField;
            }
            set {
                this.graphField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public gexfcontentVersion version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string variant {
            get {
                return this.variantField;
            }
            set {
                this.variantField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="meta-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("meta", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class metacontent {
        
        private string[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        private System.DateTime lastmodifieddateField;
        
        private bool lastmodifieddateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creator", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("description", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("keywords", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime lastmodifieddate {
            get {
                return this.lastmodifieddateField;
            }
            set {
                this.lastmodifieddateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastmodifieddateSpecified {
            get {
                return this.lastmodifieddateFieldSpecified;
            }
            set {
                this.lastmodifieddateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.gexf.net/1.2draft", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        creator,
        
        /// <remarks/>
        description,
        
        /// <remarks/>
        keywords,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="graph-content", Namespace="http://www.gexf.net/1.2draft")]
    [System.Xml.Serialization.XmlRootAttribute("graph", Namespace="http://www.gexf.net/1.2draft", IsNullable=false)]
    public partial class graphcontent {
        
        private object[] itemsField;
        
        private timeformattype timeformatField;
        
        private bool timeformatFieldSpecified;
        
        private string startField;
        
        private string startopenField;
        
        private string endField;
        
        private string endopenField;
        
        private defaultedgetypetype defaultedgetypeField;
        
        private bool defaultedgetypeFieldSpecified;
        
        private idtypetype idtypeField;
        
        private bool idtypeFieldSpecified;
        
        private modetype modeField;
        
        private bool modeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", typeof(attributescontent))]
        [System.Xml.Serialization.XmlElementAttribute("edges", typeof(edgescontent))]
        [System.Xml.Serialization.XmlElementAttribute("nodes", typeof(nodescontent))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public timeformattype timeformat {
            get {
                return this.timeformatField;
            }
            set {
                this.timeformatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeformatSpecified {
            get {
                return this.timeformatFieldSpecified;
            }
            set {
                this.timeformatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startopen {
            get {
                return this.startopenField;
            }
            set {
                this.startopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string end {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endopen {
            get {
                return this.endopenField;
            }
            set {
                this.endopenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public defaultedgetypetype defaultedgetype {
            get {
                return this.defaultedgetypeField;
            }
            set {
                this.defaultedgetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool defaultedgetypeSpecified {
            get {
                return this.defaultedgetypeFieldSpecified;
            }
            set {
                this.defaultedgetypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public idtypetype idtype {
            get {
                return this.idtypeField;
            }
            set {
                this.idtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idtypeSpecified {
            get {
                return this.idtypeFieldSpecified;
            }
            set {
                this.idtypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public modetype mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeSpecified {
            get {
                return this.modeFieldSpecified;
            }
            set {
                this.modeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="timeformat-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum timeformattype {
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        @double,
        
        /// <remarks/>
        date,
        
        /// <remarks/>
        dateTime,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="defaultedgetype-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum defaultedgetypetype {
        
        /// <remarks/>
        directed,
        
        /// <remarks/>
        undirected,
        
        /// <remarks/>
        mutual,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="idtype-type", Namespace="http://www.gexf.net/1.2draft")]
    public enum idtypetype {
        
        /// <remarks/>
        integer,
        
        /// <remarks/>
        @string,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.gexf.net/1.2draft")]
    public enum gexfcontentVersion {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.2")]
        Item12,
    }
}
